os: linux
arch: arm64-graviton2
group: edge
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - docker
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - docker-compose build --no-cache
  - docker-compose run app-test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT