os: linux
arch: arm64-graviton2
group: edge
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - docker
script:
  - docker-compose build --no-cache
  - docker-compose run app-test