version: '3'
services:
  app:
    container_name: ff-backend
    restart: always
    build: .
    ports:
      - '8080:8080'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app-test: 
    image: ff-backend_app
    command: dockerize
        -wait tcp://app:8080 -wait tcp://mongo:27017 -timeout 10s
        bash -c "npm run test"
    depends_on:
      - app
      - mongo
