version: '3'
services:
  app:
    container_name: ff-backend
    restart: always
    environment: 
      WAIT_HOSTS: mongo:27017
    build: .
    ports:
      - '8080:8080'
    external_links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  app-test: 
    image: ff-backend_app
    command: npm run test
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - app
      - mongo
